Repository Sprint-19-Rolling/frontend, pull requests merged in 2025-09, with the labels that each got.

#2 ✨ Feat:axios-instance 설정
  src/apis/README.md
  src/apis/axios.js 
Labels: ✨ Feature

#13 [🐛Fix] import logo 오류 수정
  .env.example
  src/assets/logo/logo.js
  src/assets/logo/logo.svg
Labels: 🐛 Bug

#18 [✨ Feature] tailwind 기본 설정
  .vscode/settings.json
  public/fonts/woff/Pretendard-Black.woff
  public/fonts/woff/Pretendard-ExtraBold.woff
  public/fonts/woff/Pretendard-ExtraLight.woff
  public/fonts/woff/Pretendard-Light.woff
  public/fonts/woff/Pretendard-SemiBold.woff
  public/fonts/woff/Pretendard-Thin.woff
  public/fonts/woff2/Pretendard-Black.woff2
  public/fonts/woff2/Pretendard-ExtraBold.woff2
  public/fonts/woff2/Pretendard-ExtraLight.woff2
  public/fonts/woff2/Pretendard-Light.woff2
  public/fonts/woff2/Pretendard-SemiBold.woff2
  public/fonts/woff2/Pretendard-Thin.woff2
  src/style/fonts.css
  src/style/style.css
Labels: ✨ Feature

#36 [⚙️ Chore] prop-types 패키지 설치
  package-lock.json
  package.json
Labels: ⚙️ etc

#48 ✨ Feat: font-12-medium 유틸리티 클래스 추가
  src/style/style.css
Labels: ✨ Feature

#31 ✨ Feat: 공통 컴포넌트 프로필 개별, 프로필 그룹, 페이지 컴포넌트 프로필 선택
  src/components/common/profile-image/ProfileGroup.jsx
  src/components/common/profile-image/ProfileImage.jsx
  src/components/common/profile-image/ProfileSelect.jsx
Labels: ✨ Feature

#52 ✨ Feat: Footer 컴포넌트 구현
  index.html
  src/components/common/Footer.jsx
  src/components/common/Header.jsx
  src/components/common/button/Button.jsx
  src/components/common/button/LinkButton.jsx
  src/constants/README.md
  src/constants/footer.js
  src/style/base/fonts.css
  src/style/base/style.css
  src/style/base/twUtils.css
  src/style/components/buttonStyle.js
Labels: ✨ Feature

#66 🐛 Fix: 탭 버튼 폰트 두께 수정
  src/components/post/TabButtonBox.jsx
Labels: 🐛 Bug

#61 ✨ Feat: 롤링페이퍼 작성자 정보(AuthorInfo) 컴포넌트 제작
  src/components/rolling-paper-list/AuthorInfo.jsx
Labels: ✨ Feature

#57 ✨ Feat: 공용 Input 컴포넌트 구현
  src/components/common/TextInput.jsx
  src/components/common/Title.jsx
  src/components/common/profile-image/ProfileGroup.jsx
  src/hooks/README.md
  src/hooks/useInput.js
  src/pages/Post.jsx
  src/pages/PostMessage.jsx
Labels: ✨ Feature
